// <auto-generated />
namespace EntityLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class solvedProblemTypetablewithdataset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(solvedProblemTypetablewithdataset));
        
        string IMigrationMetadata.Id
        {
            get { return "202108100729499_solvedProblemType table with data set"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
